### ISSUE TITLE
Fix tsc failure on main from unexported COMMON_STAT_CELL_COUNT

### ISSUE THREAD

**Issue by NodeJSmith** [NodeJSmith/hassette#2177]
## Description

`main` currently fails `tsc --noEmit`, which fails the `frontend` job in `tests.yml` and the
`npm run build` step in `lint.yml`'s `frontend` job. Every open PR that touches frontend paths
is blocked behind it.

```
src/components/app-detail/stat-cell-builders.test.ts(4,32): error TS2459:
Module '"./stat-cell-builders"' declares 'COMMON_STAT_CELL_COUNT' locally, but it is not exported.
```

Reproduce on a clean checkout of `main`:

```bash
cd frontend && npm install && npm run typecheck
```

Latest `tests.yml` run on `main` (`84f392d6`) is a **failure** for this reason:
https://github.com/NodeJSmith/hassette/actions/runs/34406031457

## Cause

A semantic merge conflict between two PRs that were each green on their own base:

- **#2139** (`8f5e9f5c`) changed `stat-cell-builders.test.ts` to import `COMMON_STAT_CELL_COUNT`
  from `stat-cell-builders.ts` as an exported constant.
- **#2142** (`3b25fcce`) rewrote `stat-cell-builders.ts` and left `COMMON_STAT_CELL_COUNT`
  declared as a module-local `const` with no `export`.

Neither branch contained the other's change, so neither CI run saw the broken import. Git
merged both cleanly because they touch different files.

## Fix

One word, in `frontend/src/components/app-detail/stat-cell-builders.ts:5`:

```diff
-const COMMON_STAT_CELL_COUNT = 5;
+export const COMMON_STAT_CELL_COUNT = 5;
```

The test already imports it under that exact name, and `getCommonStatCellCount()` (line 39)
continues to return it, so no other call site changes.

## Acceptance Criteria

- [ ] `cd frontend && npm run typecheck` exits 0 on `main`
- [ ] The `frontend` job in `tests.yml` passes on `main`
- [ ] `stat-cell-builders.test.ts` still imports the constant rather than re-declaring a local
      copy of the magic number (the point of #2139)

**Comment by NodeJSmith** [comment]
Autofix found nothing to change: COMMON_STAT_CELL_COUNT is already exported on main by #2189 (89a3c5f3), and `npm run typecheck` exits 0
