### PR TITLE
test: cover live WS status in the apps page stats strip

### LINKED ISSUE #1153: Stats strip on Apps page does not update in realtime when apps are started or stopped
## Description

The stats strip at the top of the Apps page (total / running / failed / stopped counts) does not update in realtime when apps are started or stopped. The individual rows and the status filter popover both apply live WebSocket status via `appStatus.value`, but `buildAppsCells()` reads `a.status` directly from the stale API payload and never receives the live override.

## Steps to Reproduce

1. Open `/apps`
2. Stop or start an app (via the action buttons or CLI)
3. The row status badge and filter popover counts update immediately
4. The stats strip counts do not update until the next full poll/refetch

## Acceptance Criteria

- [ ] The stats strip running / failed / stopped / disabled counts reflect live app status in realtime, consistent with the row badges and filter popover
- [ ] `buildAppsCells()` resolves each app's status via `appStatus.value[a.app_key]?.status ?? a.status`, mirroring the pattern used by `AppTableRow` (`liveStatus` prop) and the `statusCounts` block (lines 168–172 of `apps.tsx`)
- [ ] Tests pass — existing apps-page tests updated to cover live-status propagation to the stats strip

## Affected Areas

- `frontend/src/pages/apps.tsx` — `buildAppsCells()`: add a `liveStatusMap` parameter and apply it when counting statuses; update the call site at line ~251 to pass `appStatus.value`
- `frontend/src/pages/apps.test.tsx` — test that stats strip reflects live status overrides

### PR DESCRIPTION
**Pull request by NodeJSmith**
## Summary

Adds the missing regression test for the Apps page stats strip's live-status behavior.

The production fix for #1153 has already landed on `main`: `buildAppsCells()` takes an
`appStatuses` map and resolves each app's status through `appLiveStatus(appStatuses, a)`
(`frontend/src/pages/apps.tsx:116`), with the call site passing `appStatus`
(`apps.tsx:330`). That satisfies the issue's first two acceptance criteria. What was never
satisfied is the third — no test covered it, so the behavior was free to regress silently.

This PR closes that gap. It adds no production code.

## What changed

`frontend/src/pages/apps.test.tsx` gains one test plus a small `statValue()` helper that
reads a stats-strip cell's value by its label (the cells carry no per-label testid).

The test serves two apps with `status: "running"` from the app-grid endpoint, seeds the
store with a live `"stopped"` status for one of them, and asserts the strip renders
1 running / 1 stopped / 2 total. This mirrors the real failure mode described in the issue:
the dashboard grid query is invalidated on execution events, not `app_status_changed`, so a
cached `row.status` stays `"running"` after an app is stopped until something else forces a
refetch. The strip has to count the live status, like the row badges and filter popover do.

## Testing

- `npx vitest run src/pages/apps.test.tsx` — 20 passed
- Full frontend suite: 110 files, 1604 tests passed
- `uv run nox -s dev` — 7737 passed, 1 skipped, 2 xfailed
- `prek -a` and `prek pyright -a --stage pre-push` — clean

The test was verified to actually catch the regression, not just pass: temporarily changing
`apps.tsx:116` back to `const live = a.status;` fails it with `expected '2' to be '1'` on the
running count, exactly the bug in the issue report. The file was restored afterward.

No screenshots: the only changed file is `*.test.tsx`, which `check_pr_screenshots.py`
excludes from the visual-evidence requirement, and nothing rendered changed.

Closes #1153

### CODE REVIEW

**Comment by NodeJSmith** [comment]
@coderabbitai review

File: frontend/src/pages/apps.test.tsx [hunk 1]
```diff
@@ -70,6 +82,34 @@ describe("AppsPage", () => {
...
+      storeOverrides: {
+        ...STATE_WITH_UPTIME.storeOverrides,
+        appStatus: { [appStatusKey("b", 0)]: { status: "stopped", index: 0 } },
+      },
+    });
+
+    const strip = await findByTestId("apps-stats-strip");
+    expect(statValue(strip, "total")).toBe("2");
+    expect(statValue(strip, "running")).toBe("1");
+    expect(statValue(strip, "stopped")).toBe("1");
```
[the remark this answers is not in the document]
Comment (NodeJSmith) [reply frontend/src/pages/apps.test.tsx]: Fixed in 806dd281. Extended the test to four apps covering all four categories: `a` running (no override), `b` running→stopped, `c` running→failed, `d` disabled with a lingering per-instance `stopped` status — the last one pins that `configStatusOverride` short-circuits before `appStatuses` is consulted, which is the only way `disabled` interacts with live status at all. Verified the assertions still bite: reverting `apps.tsx:116` to `const live = a.status;` fails with `expected '3' to be '1'`.

File: frontend/src/pages/apps.test.tsx [hunk 2]
```diff
@@ -70,6 +85,46 @@ describe("AppsPage", () => {
...
+          apps: [
+            createAppGridEntry({ app_key: "a", status: "running" }),
+            createAppGridEntry({ app_key: "b", status: "running" }),
+            createAppGridEntry({ app_key: "c", status: "running" }),
+            createAppGridEntry({ app_key: "d", status: "disabled" }),
+          ],
+        }),
+      ),
+    );
+    const { findByTestId } = renderWithAppState(<AppsPage />, {
```
[the remark this answers is not in the document]
Comment (NodeJSmith) [reply frontend/src/pages/apps.test.tsx]: Fixed in bbf72b42. The test now renders against the stale REST payload only (running/running/running/disabled), asserts the initial counts, then applies the statuses post-mount via `act(() => useAppStore.getState().updateAppStatus(...))` — the same write `hooks/use-websocket.ts` makes on `app_status_changed` — and asserts the updated counts.

Confirmed the new assertion has teeth: swapping `useAppStore((s) => s.appStatus)` for `useAppStore.getState().appStatus` in `apps.tsx` makes it fail (`expected '3' to be '1'`), as does reverting `buildAppsCells` to count `a.status` instead of `appLiveStatus(...)`.

**Comment by NodeJSmith** [comment]
Overnight review pass: no changes needed on this branch.

**Review battery** (code-reviewer, integration-reviewer, wtf-reviewer, llm-checker, lazy-checker, nitpicker): 0 CRITICAL/HIGH/MEDIUM findings. Only LOW cosmetic nits (JSDoc continuation style, `for...of` vs `.find()`, hoisting selector strings to named constants). Integration review specifically checked whether `getStatValue` duplicates `health-strip.test.tsx`'s `CELL_SELECTOR` pattern and concluded it does not — that file indexes cells positionally, which isn't safe here because the apps strip's cell set is layout-dependent. Per `test-conventions.md`'s 3+ files rule, keeping the helper local is correct.

**Verification:** `npx vitest run src/pages/apps.test.tsx` → 20/20 passed; eslint and prettier clean. Mutation-checked both assertions independently:
- `apps.tsx:116` → `const live = a.status;` fails with `expected '3' to be '1'` (the #1153 stale-cache regression)
- `apps.tsx:187` → `useAppStore.getState().appStatus` fails the same way (the non-reactive-read case raised in Codex review)

**CI is red for reasons unrelated to this PR.** Every failing frontend/build/e2e check is the same pre-existing typecheck error, verified present on `origin/main` in a file this PR does not touch:

```
src/components/app-detail/stat-cell-builders.test.ts(4,32): error TS2459:
Module './stat-cell-builders' declares 'COMMON_STAT_CELL_COUNT' locally, but it is not exported.
```

That is #2177 — introduced by the #2139/#2142 merge race — and it blocks `frontend`, `build (3.13)`, all four `e2e` jobs, `lint-complete`, `tests-complete`, and `e2e-complete`. The remaining failures: `test (3.12)` is a single flaky `TimeoutError` in `test_dropped_at_drain_time_resolves_its_own_future` (3.11/3.13/3.14 all green, backend untouched here), and `file-sizes`/`duplicate-code` are the documented `continue-on-error` baseline.

Auto-merge (squash) is armed. This should go green once #2177 lands on main and checks re-run.

**Comment by NodeJSmith** [comment]
Second overnight review pass. Two comment-only fixes pushed (`398e7165`); the test logic is unchanged.

**CodeRabbit:** no unresolved threads.

**Review battery** (code-reviewer, integration-reviewer, wtf-reviewer, llm-checker, lazy-checker, nitpicker): 0 CRITICAL/HIGH. Two findings verified against the code and fixed:

- *(wtf, MEDIUM)* `apps.test.tsx:95` referenced "the issue" with no ticket pointer — unresolvable for a reader who only sees the file. Now cites `#1153`, matching the existing convention in `handlers-tab.rendering.test.tsx:95`. Per `coding-style.md`'s Self-Contained Comments rule, the link is the part worth keeping.
- *(nitpicker, LOW)* the `getStatValue` JSDoc used two-space continuation indents; 66 of 69 frontend files with multi-line JSDoc use one space. Normalized.

Findings deliberately skipped, both judgment calls: hoisting the five stat-label literals into constants (test-local, and inline labels keep the assertion failure messages readable), and collapsing the two five-line assertion blocks into an `expectCounts()` helper (lazy-checker itself noted it's "arguably clearer as-is").

**Verification:** `npx vitest run src/pages/apps.test.tsx` → 20/20; full frontend suite → 110 files / 1604 tests passed; eslint, prettier, and `tsc --noEmit` clean on the branch. Both assertions mutation-checked independently — reverting `apps.tsx:116` to `const live = a.status;` fails with `expected '3' to be '1'` (the #1153 stale-cache bug), and making the `appStatus` store read non-reactive fails identically. `apps.tsx` was restored to its committed state after each check.

**CI red is inherited from `main`, not this PR.** Verified directly rather than taken on trust: on current `origin/main`, `stat-cell-builders.ts:5` declares `COMMON_STAT_CELL_COUNT` without `export` while `stat-cell-builders.test.ts:4` imports it. At this branch's HEAD the symbol *is* exported and the test does not import it, so the break only materializes in the PR merge commit — which is why `tsc --noEmit` is clean here but red in CI. That is #2177, and it blocks `frontend`, `build (3.13)`, all four `e2e` jobs, `lint-complete`, `tests-complete`, and `e2e-complete`. `test (3.12)` is a backend job and this PR's diff touches zero backend files. `file-sizes`/`duplicate-code` are the documented `continue-on-error` baseline.

Auto-merge (squash) remains armed; this should go green once #2177 lands on `main`.

**Comment by NodeJSmith** [comment]
Automated review has run 3 time(s) on this PR without it reaching a mergeable state. Converting to draft and labeling for a human decision rather than retrying indefinitely — see hassette_review_autofixes.py's escalate_pr().
